fieldLayouts:
  0359e311-f4eb-4a4a-ac58-aea079d7d21d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0f9e3f8a-ab89-4a0e-9b1a-9333b6c8a901
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63534776-7c72-4b5b-a2d9-f870d1bce7b2 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6818075b-aa0f-4633-ade7-1167a8bc20ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cefbbf34-4b06-4592-a34b-3585adc0bdfe # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c98db1b6-72f6-4876-967e-aea3a7e51779
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 637eccaf-aa07-456f-a139-06e465b25028
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fcade7fb-fe4a-4937-8692-661df59177f0 # Featured Story
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4a7b510-9b5b-46af-a595-a74d6afd7e5f
            userCondition: null
            warning: null
            width: 100
        name: 'Featured Story'
        uid: 4fbe277b-a89c-427d-b3ef-d6e792cd9ef0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d1b5d898-93ca-42f0-92f2-e69bc99cad3b # Riders Intro Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc5a1bdc-8a4e-4cc4-9904-bf9009aaf6ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c10201fd-ec75-4c06-a94c-0811a3e8d457 # Riders
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84c37a18-a531-499a-b721-3cb3a40f9608
            userCondition: null
            warning: null
            width: 100
        name: Riders
        uid: 9c38c85c-7f85-4dd0-949c-744ade590baf
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 3abfa5c6-c879-4c64-8f03-b00943c7665c # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
