fieldLayouts:
  32510888-08b7-4a5d-97c2-66fd7dbb1025:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 43ca6dd3-505e-41b8-ab67-9e8f22d14f9b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f945ad3-dab2-4fe7-a308-852cde050e1e
        userCondition: null
handle: storiesListing
hasTitleField: true
name: 'Stories Listing'
section: 519f4587-a342-4241-951e-f3a14b578ada # Stories Listing
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
