columnSuffix: null
contentColumnType: string
fieldGroup: 049f0604-df55-4a1d-884a-9a952351e75f # Common
handle: navLinks
instructions: null
name: 'Nav Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navlinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
