columnSuffix: null
contentColumnType: string
fieldGroup: 9e8b5d30-88e1-469a-939f-67489e11890a # Home Page
handle: riders
instructions: null
name: Riders
searchable: false
settings:
  contentTable: '{{%matrixcontent_riders}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
