fieldLayouts:
  f26557bd-fd63-42a7-b405-19393011175e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 995187d5-d494-4cb3-bd2b-bc60ff60f8e7 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b336e5a6-b3dc-4150-94b0-54f7131724e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c4bf10e-af7f-46f3-a4fc-7955a8038d6b
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
