defaultPlacement: end
enableVersioning: true
handle: generalPages
name: 'General Pages'
propagationMethod: all
siteSettings:
  f9d25293-4b12-4128-be7e-6bb4642611e1: # Crafty Motoventure
    enabledByDefault: true
    hasUrls: true
    template: general.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: 0676f921-5e1d-43ce-ad17-5009420c9c9e
type: structure
